### PR TITLE
add missing en-US fulldesc and de shortdesc to Fastlane

### PR DESCRIPTION
**Pull request by IzzySoft**
For your MR with F-Droid :wink:

### CODE REVIEW

**Comment by machiav3lli** [comment]
The feedback is actually viceversa (accent color (red or orange) is true and (blue or nile) is false) but as a wise (wo)man once said: "es ist eigentlich egal". 
Thanks, I was losing hope that its time will come.

**Comment by IzzySoft** [comment]
Aw well… ich hab nur das kopiert, was ich für die ursprüngliche App bei mir hatte. Ich benutze sie selbst nicht, daher… feel free to adjust :smile:

And yes, I'm on a triage run at the MRs. What runs most are my tears; I didn't expect things being in that bad a shape. Several devs must feel abandoned/neglected/forgotten… So I take my tears, polish them, and turn them to bribes: Offering PRs like this, taking apps into my repo (just ask and provide the APK, I'll do the same here), pushing our packagers, threaten to hit merge buttons myself :speak_no_evil: Nope – the latter I wouldn't dare. Our team is already "unter Wasser".

**Comment by machiav3lli** [comment]
Feel free to add it into your repo. If I recall right, you've been asking for the License before I wrote the original developer an email for that.
I'll be updating some resources and publishing a new point release tonight (in the next 45 minutes) with the apk on it.
so, Nighty.

**Comment by IzzySoft** [comment]
Done :smiley: It can take care for the update itself. Including Fastlane.

**Comment by IzzySoft** [comment]
Now that your app went live on F-Droid, shall I still keep it in mine? I usually give it a week overlap and then remove it, unless explicitly wished otherwise (some [background here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ)).

Also: you've noticed the display issues I reported? Please do not forget :wink:

**Comment by machiav3lli** [comment]
Moin moin. You can gladly keep it in the repo, as, as it stands, your repo is still the first to get the update days earlier, even if FDroid improved their updates cycle.

I'll cover the mentioned issues in future releases, it's just that am short on time right now. On other matter, nice video on FDroid contributions. Have a nice day.

**Comment by IzzySoft** [comment]
Thanks! Marked it to be kept (note for "double listing" should show up in my repo browser after the next sync, linking here for reference).

Thanks for taking care about the mentioned issues – and glad you liked the video! Hopefully more to come (and hopefully the instance admins wake up soon to renew their certificate!)

**Pull request merged**
